[package]
name = "worker"
edition.workspace = true
version.workspace = true
publish.workspace = true

[[bin]]
name = "worker"
path = "src/main.rs"

[dependencies]
application = { path = "../application" }
domain = { path = "../domain" }
infrastructure = { path = "../infrastructure" }

anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
cron.workspace = true
dotenvy.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
metrics-process.workspace = true
sqlx.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true